name: Configure windows environment and publish

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  deploy:
    name: build and run
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: download code and run
        env:
          TZ: Asia/Shanghai
        run: |
          move scripts/config_env.bat ./
          move scripts/publish.bat ./
      
      - name: Configure Environments
        run: |
          ./config_env.bat

      - name: Publish Release
        run: |
          ./publish.bat


  upload:
    name: Upload Windows Release
    runs-on: ubuntu-latest
    needs: deploy
    # 只在tag时执行，即在自己终端运行以下代码后触发
    # git tag -a v0.1.0 -m "release 0.1.0 version"
    # git push origin --tags
    if: contains(github.ref, 'tags/')
    steps:
      - name: Prepare Release
        id: prepare_release
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo ::set-output name=tag_name::$TAG_NAME
      - name: Create Windows Release
        run: |
          mv QrScan.zip QrScan_windows_${{steps.prepare_release.outputs.tag_name}}.zip
      - name: Upload Windows Release
        uses: softprops/action-gh-release@v1
        with:
          files: QrScan_windows_${{steps.prepare_release.outputs.tag_name}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}