name: Ubuntu

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  deploy:
    name: build and run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: download code and run
        env:
          TZ: Asia/Shanghai
        run: |
          sudo apt update && sudo apt install python3-pip python3-venv zip unzip
          mv scripts/config_env.sh ./
          mv scripts/publish.sh ./
      
      - name: Configure Environments
        run: |
          chmod +x config_env.sh
          ./config_env.sh

      - name: Publish Release
        run: |
          chmod +x publish.sh
          ./publish.sh

      - name: Upload release file
        if: contains(github.ref, 'tags/')
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: QrScan.zip
          retention-days: 1


  upload:
    name: Upload Ubuntu Release
    runs-on: ubuntu-latest
    needs: deploy
    # 只在tag时执行，即在自己终端运行以下代码后触发
    # git tag -a v0.1.0 -m "release 0.1.0 version"
    # git push origin --tags
    if: contains(github.ref, 'tags/')
    steps:
      - name: Download release file
        uses: actions/download-artifact@v3
        with:
          name: release
      - name: Create Ubuntu Release
        run: |
          mv QrScan.zip QrScan_linux_${{ github.ref_name }}.zip
      - name: Upload Ubuntu Release
        uses: softprops/action-gh-release@v1
        with:
          files: QrScan_linux_${{ github.ref_name }}.zip